inmobiliaria/urls.py
from django.contrib import admin
from django.urls import path, include
from inmueble import views

# Modulo para buscar archivos en el proyecto
from django.conf.urls.static import static

# Importa el contenido del archivo settings.py
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Ruta de la página de Inicio
    path('', views.home, name='inicio'),

    # Ruta que busca inmuebles
    path('buscar/', views.Busqueda, name='buscar'),

    # Ruta de la página Nosotros
    path('paginas/nosotros/', views.nosotros, name='nosotros'),

    # Ruta de la página Contacto
    path('paginas/contacto/', views.ContactoView.as_view(), name='contacto'),

    # Ruta de la página de ventas
    path('paginas/ventas/', views.VentaList.as_view(), name='ventas'),

    # Ruta de la página de arrendamientos
    path('paginas/arrendamientos/', views.AlquilerList.as_view(), name='arrendamientos'),

    # Ruta de la página para crear inmuebles
    path('crear/', views.Guardar_inmueble, name='crear'),

    # Ruta de la página para listar los inmuebles
    path('listar/', views.Listar_inmueble, name='listar'),

    # Ruta de la página para editar los inmuebles
    path('<int:pk>/', views.Editar_inmueble, name='editar'),

    # Ruta de la página que muestra información de cada inmueble (Detail)
    path('detalle/<int:pk>/', views.InmuebleDetail.as_view(), name='detalle'),

    # Ruta de la página para gestionar los proietarios y sus inmuebles
    path('asesor/gestion_inmueble/', views.GestionCreate.as_view(), name='gestion'),

    # Ruta de la página que muestra los propietarios y sus inmuebles
    path('asesor/inmuebles/', views.GestionList.as_view(), name='listar_gestion'),

    # Ruta de la página mis inmuebles
    path('cliente/mis_inmuebles/', views.MisinmueblesList.as_view(), name='mis_inmuebles'),

    # Ruta de la página que envía un mensaje al asesor
    path('cita/', views.Citas_inmuebles.as_view(), name='cita'),

    # Ruta de la página que muestra los mensajes al asesor
    path('asesor/mis_citas/', views.CitaList.as_view(), name='mis_citas'),

    # Ruta de la página para eliminar la cita
    path('eliminar/<int:pk>/', views.CitaDelete.as_view(), name='eliminar_cita'),

    # Ruta del inicio de sesión
    path('accounts/', include('django.contrib.auth.urls')),

    # Ruta de las urls de la aplicación usuario
    path('usuario/', include(('usuario.urls', 'usuario'), namespace='usuario')),
]

# Concatenación para buscar archivos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
#UserUpdate

urlpatterns = [

    # Ruta de la página de registro de usuario
    path('signup/', views.signup, name='signup'),

    # Ruta de la página de para realizar la activación de la cuenta
    path('emailsent/<str:username>/', views.templateEmailSent, name='emailsent'),

    # Ruta de la página que muestra la cuenta activada
    path('activate/<str:uidb64>/<str:token>/', views.ActivateUser, name='activate'),

]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Inmobiliaria</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  </head>
  <body>
    <nav class="white" role="navigation">
      <div class="nav-wrapper container">
        <img src="{% static 'img/Logo5.png' %}" style="width: 100px; height: 64px">
        <a id="logo-container" class="brand-logo">
          <span class="black-text text-darken-2"><i>Innova Inmobiliaria</i></span></a>
        <ul class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
            <!-- Dropdown Trigger -->
            <li>
              <a class='dropdown-trigger black-text' href='#' data-target='dropdown1'>
                  <i class="material-icons right">face</i>
                  <span class="black-text text-darken-2">Perfil</span>
              </a>
            </li>

              <!-- Dropdown Structure -->
              <ul id='dropdown1' class='dropdown-content'>
                {% if user.perfil.IDRol.nombre == "Asesor" %}
                  <li><h6>{{ user.perfil.IDRol.nombre }} {{ user.username }}</h6></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'gestion' %}">Gestión de la propiedad</a></li>
                  <li><a href="{% url 'listar_gestion' %}">Inmuebles y propietarios</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'crear' %}">Ingreso de inmuebles</a></li>
                  <li><a href="{% url 'listar' %}">Listado de inmuebles</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'mis_citas' %}">Mis citas</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% else %}
                  <li><h6>{{ user.perfil.IDRol.nombre }} {{ user.username }}</h6></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'mis_inmuebles' %}">Mis inmuebles</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% endif %}
              </ul>
          {% else %}
            <li>
              <a href="{% url 'usuario:signup' %}">
                <span class="black-text text-darken-2">Registrarse</span>
              </a>
            </li>
            <li>
              <a href="{% url 'login' %}" class="black-text">
                <i class="material-icons right">account_circle</i>
                <span class="black-text text-darken-2">Ingresar</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <nav class="nav-extended red darken-2 white-text" >
      <div class="nav-wrapper">
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="hide-on-med-and-down">
          <li><a href="{% url 'inicio' %}"><b>INICIO</b></a></li>
          <li><a href="{% url 'ventas' %}"><b>VENTAS</b></a></li>
          <li><a href="{% url 'arrendamientos' %}"><b>ARRENDAMIENTOS</b></a></li>
          <li><a href="{% url 'nosotros' %}"><b>NOSOTROS</b></a></li>
          <li><a href="{% url 'contacto' %}"><b>CONTACTO</b></a></li>
        </ul>
      </div>
    </nav>
    <nav>
      <div class="nav-wrapper container">
        <form method="get" action="{% url 'buscar' %}"> {% csrf_token %}
            <div class="input-field">
              <input id="search" type="search" name="buscar" placeholder="Buscar..." required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            </div>
        </form>
      </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
      <li><a href="{% url 'inicio' %}">INICIO</a></li>
      <li><a href="{% url 'ventas' %}">VENTAS</a></li>
      <li><a href="{% url 'arrendamientos' %}">ARRENDAMIENTOS</a></li>
      <li><a href="{% url 'nosotros' %}">NOSOTROS</a></li>
      <li><a href="{% url 'contacto' %}">CONTACTO</a></li>
    </ul>

    <div class="container">
      {% block container %}
      {% endblock %}
    </div>


      {% block container2 %}
      {% endblock %}



  </body>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>

  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

  <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
        $('select').formSelect();
        $('.tabs').tabs();
        $(".dropdown-trigger").dropdown();
        $('.modal').modal();
      });

      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.slider');
        var instances = M.Slider.init(elems, {
          indicators: false,
          height: 450,
        });
        var elems = document.querySelectorAll('.parallax');
        var instances = M.Parallax.init(elems, {
          responsiveThreshold: 0
        });
      });
  </script>
  <footer class="page-footer red lighten-1 white-text">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h4>Ubicación</h4>
            <h6>Dirección: Calle 64A N°21-10 Oficina 202 Ed Portal del Cable</h6>
            <h6>Teléfono: 8894521</h6>
            <h6>Celular: 3165874219</h6>
            <h6>Correo: inmobiliariainnova@gmail.com</h6>
          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Enlaces</h5>
            <ul>
              <li><a class="white-text text-lighten-3" href="{% url 'ventas' %}">VENTAS</a></li>
              <li><a class="white-text text-lighten-3" href="{% url 'arrendamientos' %}">ARRENDAMIENTOS</a></li>
              <li><a class="white-text text-lighten-3" href="{% url 'nosotros' %}">NOSOTROS</a></li>
              <li><a class="white-text text-lighten-3" href="{% url 'contacto' %}">CONTACTO</a></li>
            </ul>
          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Redes Sociales</h5>
            <ul>
              <li>
                <img src="{% static 'img/Icono Facebook.png' %}" style="width:24px; height:24px;">
                <img src="{% static 'img/Icono Instagram.png' %}" style="width:30px; height:24px;">
                <img src="{% static 'img/Icono Twitter.png' %}" style="width:24px; height:24px;">
                <img src="{% static 'img/Icono Whatsapp.png' %}" style="width:32px; height:24px;">
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2020 Todos los derechos reservados
        <a class="grey-text text-lighten-4 right">Diseñado y desarrollado por AVWeb</a>
        </div>
      </div>
  </footer>
</html>